//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MusicPiece
    {
        public int RecordNumber { get; set; }
        public int NamingConventionID { get; set; }
        public int ComposerID { get; set; }
        public Nullable<int> Difficulty { get; set; }
        public Nullable<int> Year { get; set; }
        public string Instrument { get; set; }
    
        public virtual Composer Composer { get; set; }
        public virtual OpusNamingConvention OpusNamingConvention { get; set; }
    }
}
