//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MusicWebsite.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class view_MusicPieces
    {
        public Nullable<int> Difficulty { get; set; }
        public int RecordNumber { get; set; }
        public Nullable<int> Year { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string FullName { get; set; }
        public string PieceName { get; set; }
        public int ComposerID { get; set; }
    }
}
